development:
  adapter: postgresql
  database: tdf-development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: tdf-test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: tdf-production
  pool: 5
  timeout: 5000
