development:
  adapter: postgresql
  database: tdf_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: tdf_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: tdf_production
  pool: 5
  timeout: 5000
