require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe RidesController do

  def mock_ride(stubs={})
    @mock_ride ||= mock_model(Ride, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all rides as @rides" do
      Ride.stub(:all) { [mock_ride] }
      get :index
      assigns(:rides).should eq([mock_ride])
    end
  end

  describe "GET show" do
    it "assigns the requested ride as @ride" do
      Ride.stub(:find).with("37") { mock_ride }
      get :show, :id => "37"
      assigns(:ride).should be(mock_ride)
    end
  end

  describe "GET new" do
    it "assigns a new ride as @ride" do
      Ride.stub(:new) { mock_ride }
      get :new
      assigns(:ride).should be(mock_ride)
    end
  end

  describe "GET edit" do
    it "assigns the requested ride as @ride" do
      Ride.stub(:find).with("37") { mock_ride }
      get :edit, :id => "37"
      assigns(:ride).should be(mock_ride)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created ride as @ride" do
        Ride.stub(:new).with({'these' => 'params'}) { mock_ride(:save => true) }
        post :create, :ride => {'these' => 'params'}
        assigns(:ride).should be(mock_ride)
      end

      it "redirects to the created ride" do
        Ride.stub(:new) { mock_ride(:save => true) }
        post :create, :ride => {}
        response.should redirect_to(ride_url(mock_ride))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved ride as @ride" do
        Ride.stub(:new).with({'these' => 'params'}) { mock_ride(:save => false) }
        post :create, :ride => {'these' => 'params'}
        assigns(:ride).should be(mock_ride)
      end

      it "re-renders the 'new' template" do
        Ride.stub(:new) { mock_ride(:save => false) }
        post :create, :ride => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested ride" do
        Ride.stub(:find).with("37") { mock_ride }
        mock_ride.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :ride => {'these' => 'params'}
      end

      it "assigns the requested ride as @ride" do
        Ride.stub(:find) { mock_ride(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:ride).should be(mock_ride)
      end

      it "redirects to the ride" do
        Ride.stub(:find) { mock_ride(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(ride_url(mock_ride))
      end
    end

    describe "with invalid params" do
      it "assigns the ride as @ride" do
        Ride.stub(:find) { mock_ride(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:ride).should be(mock_ride)
      end

      it "re-renders the 'edit' template" do
        Ride.stub(:find) { mock_ride(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested ride" do
      Ride.stub(:find).with("37") { mock_ride }
      mock_ride.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the rides list" do
      Ride.stub(:find) { mock_ride }
      delete :destroy, :id => "1"
      response.should redirect_to(rides_url)
    end
  end

end
